version: '3'

services:
  dev-phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: dev-phpmyadmin
    # links:
    #   - 'smu-db:db'
    ports:
    - 3803:80
    environment:
      PMA_ARBITRARY: 1

  dev-adminer:
    image: adminer
    restart: always
    container_name: dev-mysql-adminer
    # links:
    #   - 'smu-db:db'
    ports:
      - 3804:8080
    # mem_limit: 2G
    environment:
      ADMINER_DESIGN: 'nette'
    volumes:
      - './artifacts/0-upload_large_dumps.ini:/usr/local/etc/php/conf.d/0-upload_large_dumps.ini'

networks:
  default:
    external: true
    name: 'development'
